import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';import {clean,review} from '../../src/examples.mjs';import {archive,container} from '../helpers.mjs';import {score,note} from '../helpers.mjs';
const out='tests/browser/artifacts';await mkdir(out,{recursive:true});const completed=[],errors=[],requests=[];
const browser=await chromium.launch({headless:true,chromiumSandbox:true});const base=process.env.BASE_URL||'http://127.0.0.1:4175';
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>requests.push(r.url()));
const step=async(name,fn)=>{await fn();completed.push(name);console.log('PASS '+name);};
const importScore=async(xml,name='test.musicxml')=>{await page.locator('#file').setInputFiles({name,mimeType:'application/xml',buffer:Buffer.from(xml)});await expect(page.locator('#loading')).toBeHidden();await expect(page.locator('#notice')).not.toHaveClass(/error/);await expect(page.locator('.file-heading h2')).toHaveText(name);};
async function download(id,name){const pending=page.waitForEvent('download');await page.locator('#'+id).click();const d=await pending;const path=`${out}/${name}`;await d.saveAs(path);return await readFile(path,'utf8');}
try{
await step('Japanese initial, keyboard skip, demos and English navigation',async()=>{await page.goto(base);await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('.empty')).toBeVisible();await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#workspace')).toBeFocused();await page.locator('#demo-review').click();await expect(page.locator('.file-heading h2')).toHaveText('demo-review.musicxml');await expect(page.locator('.measure-button')).toHaveCount(6);await page.screenshot({path:`${out}/desktop-ja.png`,fullPage:true});await page.locator('[data-lang="en"]').click();await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('#notice')).toContainText('Imported');});
await step('duplicate measure labels are distinguished by ordinal and source evidence',async()=>{await page.locator('#measure').selectOption('2');await expect(page.locator('.measure-heading h2')).toContainText('Measure #3');await expect(page.locator('.finding')).toContainText('chord-too-long');await page.locator('.finding summary').first().click();await expect(page.locator('.finding pre').first()).toContainText('<chord/>');await page.locator('[data-event="2"]').click();await expect(page.locator('#event-2')).toHaveAttribute('open','');await expect(page.locator('#event-2 summary')).toBeFocused();await page.screenshot({path:`${out}/desktop-en-evidence.png`,fullPage:true});});
await step('unsupported state never appears as a green verdict and filter is reversible',async()=>{await page.locator('#measure').selectOption('4');await expect(page.locator('.measure-heading .badge')).toHaveClass(/unsupported/);await expect(page.locator('.metrics')).toContainText('Not calculated');await page.locator('#filter').selectOption('attention');await expect(page.locator('.measure-button')).toHaveCount(6);await page.locator('#filter').selectOption('all');await page.locator('#demo-clean').click();await expect(page.locator('.measure-button')).toHaveCount(3);await page.locator('#filter').selectOption('attention');await expect(page.locator('.measure-list')).toContainText('No matching');await page.locator('#filter').selectOption('all');});
await step('reset cancellation, replacement and repeated same-file imports',async()=>{await page.locator('#reset').click();await expect(page.locator('#reset-dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#reset-dialog')).toBeHidden();await expect(page.locator('.measure-button')).toHaveCount(3);for(let i=0;i<2;i++)await importScore(review,'repeat.musicxml');await expect(page.locator('.measure-button')).toHaveCount(6);await page.locator('#file').setInputFiles({name:'broken.xml',mimeType:'application/xml',buffer:Buffer.from('<broken>')});await expect(page.locator('#notice')).toHaveClass(/error/);await expect(page.locator('.file-heading h2')).toHaveText('repeat.musicxml');});
await step('real MXL deflate, rootfile selection and error retention',async()=>{await page.locator('#file').setInputFiles({name:'test.mxl',mimeType:'application/vnd.recordare.musicxml',buffer:archive([['META-INF/container.xml',container('nested/score.musicxml')],['nested/score.musicxml',clean]])});await expect(page.locator('.file-heading h2')).toHaveText('test.mxl');await page.locator('.fingerprint summary').click();await expect(page.locator('.fingerprint')).toContainText('nested/score.musicxml');await page.locator('#file').setInputFiles({name:'unsafe.mxl',mimeType:'application/vnd.recordare.musicxml',buffer:archive([['../score.musicxml',clean]])});await expect(page.locator('#notice')).toContainText('zip-path');await expect(page.locator('.file-heading h2')).toHaveText('test.mxl');});
await step('interrupted worker import, newer import wins and reset cannot resurrect old result',async()=>{await page.evaluate(()=>{window.__postMessage=Worker.prototype.postMessage;const original=window.__postMessage;Worker.prototype.postMessage=function(...args){setTimeout(()=>{try{original.apply(this,args);}catch{}},400);};});await page.locator('#demo-review').click();await expect(page.locator('#loading')).toBeVisible();await page.locator('#cancel').click();await expect(page.locator('.file-heading h2')).toHaveText('test.mxl');await page.evaluate(()=>{Worker.prototype.postMessage=window.__postMessage;delete window.__postMessage;});await page.locator('#demo-review').click();await expect(page.locator('.file-heading h2')).toHaveText('demo-review.musicxml');await page.locator('#demo-clean').click();await page.locator('#demo-review').click();await expect(page.locator('.file-heading h2')).toHaveText('demo-review.musicxml');await expect(page.locator('.measure-button')).toHaveCount(6);await page.locator('#reset').click();await page.locator('#confirm-reset').click();await expect(page.locator('.empty')).toBeVisible();});
await step('oversized replacement invalidates an interrupted generation and retains the last completed result',async()=>{await importScore(clean,'retained.musicxml');await page.evaluate(()=>{window.__postMessage=Worker.prototype.postMessage;const original=window.__postMessage;Worker.prototype.postMessage=function(...args){setTimeout(()=>{try{original.apply(this,args);}catch{}},400);};});await page.locator('#demo-review').click();await expect(page.locator('#loading')).toBeVisible();await page.locator('#file').setInputFiles({name:'oversized.musicxml',mimeType:'application/xml',buffer:Buffer.alloc(8*1024*1024+1)});await expect(page.locator('#notice')).toContainText('input-size');await expect(page.locator('#loading')).toBeHidden();await expect(page.locator('.file-heading h2')).toHaveText('retained.musicxml');await page.evaluate(()=>{Worker.prototype.postMessage=window.__postMessage;delete window.__postMessage;});await page.waitForTimeout(600);await expect(page.locator('#notice')).toContainText('input-size');await expect(page.locator('.file-heading h2')).toHaveText('retained.musicxml');});
await step('offline import and actual JSON / bilingual HTML downloads',async()=>{await context.setOffline(true);await importScore(review,'offline.musicxml');const json=JSON.parse(await download('json','review.json'));assert.equal(json.parts[0].measures.length,6);assert.match(json.input.sha256,/^[a-f0-9]{64}$/);assert.equal(json.findingDescriptions['chord-too-long'].ja.length>0,true);const html=await download('html','review.html');assert.match(html,/Rhythm handoff review/);assert.match(html,/リズム引き継ぎレポート/);assert.ok(html.includes(json.input.sha256));const report=await context.newPage();await report.setContent(html);await expect(report.locator('script')).toHaveCount(0);await expect(report.locator('.measure')).toHaveCount(6);await report.emulateMedia({media:'print'});await report.pdf({path:`${out}/review.pdf`,format:'A4',printBackground:true});await report.screenshot({path:`${out}/report-print.png`,fullPage:true});await report.close();await context.setOffline(false);});
await step('hostile imported text, DTD and external assets execute nothing and fetch nothing',async()=>{const hostile=score(note(48)).replace('Test','&lt;img src=x onerror=alert(1)&gt;').replace('<score-partwise>','<!DOCTYPE score-partwise SYSTEM "https://blocked.invalid/dtd"><score-partwise>').replace('<part-list>','<credit><credit-image source="https://blocked.invalid/remote.svg"/></credit><part-list>');await importScore(hostile,'hostile.musicxml');await expect(page.locator('.navigator img')).toHaveCount(0);await expect(page.locator('.measure-heading')).toContainText('<img');assert.ok(!requests.some(r=>r.includes('blocked.invalid')));const html=await download('html','hostile.html');assert.ok(!html.includes('<img src=x'));});
await step('long Japanese labels and responsive screens stay within the viewport',async()=>{await importScore(clean.replace('クラリネット / Clarinet','長いパート名'.repeat(35)),'長いファイル名'.repeat(25)+'.musicxml');for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);await page.screenshot({path:`${out}/responsive-${width}.png`,fullPage:true});}await page.setViewportSize({width:1440,height:1000});});
await step('screen print makes selected-measure scope explicit and preserves visible evidence',async()=>{await page.locator('#demo-review').click();await expect(page.locator('.file-heading h2')).toHaveText('demo-review.musicxml');await page.locator('#measure').selectOption('2');await page.emulateMedia({media:'print'});await expect(page.locator('.screen-print-note')).toBeVisible();await expect(page.locator('.scope')).toBeVisible();await page.pdf({path:`${out}/selected-measure.pdf`,format:'A4',printBackground:true});await page.screenshot({path:`${out}/screen-print.png`,fullPage:true});await page.emulateMedia({media:'screen'});});
await step('no persisted score after reload, no duplicate IDs or uncaught errors',async()=>{assert.equal(await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(n=>n.id);return ids.length===new Set(ids).size;}),true);await page.reload();await expect(page.locator('.empty')).toBeVisible();assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith(base+'/')||u.startsWith('blob:')));});
await writeFile(`${out}/results.json`,JSON.stringify({status:'passed',chromiumSandbox:true,checks:completed,uncaughtErrors:errors},null,2));
}catch(error){await page.screenshot({path:`${out}/failure.png`,fullPage:true}).catch(()=>{});await writeFile(`${out}/results.json`,JSON.stringify({status:'failed',chromiumSandbox:true,checks:completed,error:String(error),uncaughtErrors:errors},null,2));throw error;}finally{await context.close();await browser.close();}
